services:
  db:
    container_name: chat-with-me_db
    image: postgres
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: chat-with-me_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: "exit 0"
    ports:
      - "5232:5432"